### ISSUE TITLE
Message text

### ISSUE THREAD

**Issue by RajeshMaapu** [rodrigogs/occupy-sarahah#1]
Can we flood the profile with text messages in English and emoji's ?

**Comment by rodrigogs** [comment]
Unfortunally, no :/

But it's very easy to change the content that is sent if you have some programmer skills.

**Comment by RajeshMaapu** [comment]
Yeah. Looking into that now. Thank you.

**Comment by rodrigogs** [comment]
After changing the code, just execute `npm link` to make it available globaly
